### ISSUE TITLE
Prevent obvious redirect loop in rules validation

### ISSUE THREAD

**Issue by shylux** [4teamwork/ftw.redirector#2]
Currently it's possible to redirect to itself. This could be prevented in the rules validation.
![screen shot 2015-11-18 at 08 58 43](https://cloud.githubusercontent.com/assets/1375745/11235570/e6dc6396-8dd2-11e5-911a-70b6a5c12069.png)
![screen shot 2015-11-18 at 09 01 25](https://cloud.githubusercontent.com/assets/1375745/11235590/02c5dfec-8dd3-11e5-8746-6d4b74a880a3.png)

**Comment by jone** [comment]
I already thought about that, but I decided to leave it unsolved for now.
The reason is that the problem can get quite complex.
If we detect simple redirect loops (`/foo`->`/foo`) that's great, but the we should also detect more complex redirect loops (`/foo` -> `/bar` -> `/baz` -> `/foo`), so we'd need to do some graph work here in order to detect circular dependencies.
But wait: we do not have all redirects in this configuration. Some redirects may come from plone.app.redirector (because of moved objects) or may not be visible here.
I'd also add regex-support later, what about `/f*` -> `/foo`? This can produce redirect loops, but it not in any case..

My decision was to not support any detection for now, since it is a promise I cannot hold. And the obvious redirect loops are quite obvious to anybody, right? :wink:

**Comment by shylux** [comment]
I'm aware that we can't detect all loops. I wanted to prevent just the obvious mistakes.
But i see your point. I think too, that a limited detection may bring more harm than merit.
